### ISSUE TITLE
BuildInfo is always saying deploy artifacts is set to false 

### ISSUE THREAD

**Issue by pramodbiligiri** [jfrog/jfrog-cli#1094]
**Describe the bug**
I am not able to deploy from a Github Actions workflow file to a Jfrog-GCP repo (hosted at bkjfrog.jfrog.io), because the BuildInfoExtractor keeps deciding that publish flags are set to false:
```
[main] INFO org.jfrog.build.extractor.maven.BuildDeploymentHelper - Artifactory Build Info Recorder: Saving Build Info to '/home/runner/work/tts-model/tts-model/target/build-info.json'
[main] INFO org.jfrog.build.extractor.maven.BuildDeploymentHelper - Artifactory Build Info Recorder: deploy artifacts set to false, artifacts will not be deployed...
[main] INFO org.jfrog.build.extractor.maven.BuildDeploymentHelper - Artifactory Build Info Recorder: publish build info set to false, build info will not be published..
```
The relevant part of the Github actions file looks like this:
```
      - name: push to JFrog
        uses: jfrog/setup-jfrog-cli@v1.2.0
        with:
          version: 1.48.1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JFROG_KEY }}
          M2_HOME: /usr/share/apache-maven-3.8.1
          JFROG_CLI_LOG_LEVEL: DEBUG
          buildInfo.env.publisher.publishArtifacts: true
          buildInfo.env.publisher.publishBuildInfo: true
      - run: |
          M2_HOME=/usr/share/apache-maven-3.8.1 jfrog rt mvnc
          M2_HOME=/usr/share/apache-maven-3.8.1 jfrog rt mvn clean install
          M2_HOME=/usr/share/apache-maven-3.8.1 jfrog rt bp
```

**Versions**
- Can be seen in the workflow snippet above

**Additional context**
I am trying setting various buildInfo env vars but without any success.
