### ISSUE TITLE
NPM Postinstall Script Fails

### ISSUE THREAD

**Issue by samrjfrog** [jfrog/jfrog-cli#1304]
**Describe the bug**
The JFrog CLI sometimes fails to install esbuild (versions before 0.13.0) 

**To Reproduce**
Create an NPM package.json with esbuild@0.12.24 as a dependency. Configure the jfrog CLI npm entension to use Artifactory. Install the package dependencies with the CLI.

**Expected behavior**
The package esbuild@0.12.24 is installed from the Artifactory remote npm repository

**Actual behavior**
The npm client receives a 401 error from Artifactory and instead installs the package directly from https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.12.24.tgz

**Logs**
```
> esbuild@0.12.24 postinstall /home/vsts/work/1/s/npm-example/node_modules/esbuild
> node install.js
 
Trying to install "esbuild-linux-64" using npm
Failed to install "esbuild-linux-64" using npm: Command failed: npm install --loglevel=error --prefer-offline --no-audit --progress=false esbuild-linux-64@0.12.24
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="Artifactory Realm"
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vsts/.npm/_logs/2021-11-22T14_46_18_878Z-debug.log
 
Trying to download "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.12.24.tgz"
Install successful
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN npm-example@0.0.3 No repository field.
npm WARN npm-example@0.0.3 No license field.
 
added 20 packages from 15 contributors and audited 20 packages in 5.188s
found 0 vulnerabilities
```

**Versions**
- JFrog CLI version: 2.5.0
- JFrog CLI operating system: Ubuntu 18
- Artifactory Version: 7.27

**Additional information**
This issue reproduces intermittently via the CLI. When building the project via the Azure Devops Artifactory extension, it fails every time. Here is a sample package.json that fails

Here’s the pipeline configuration that fails:
```
# Starter pipeline
steps:
- task: ArtifactoryNpm@2
 inputs:
   command: 'install'
   artifactoryService: 'samr-jfrog-io'
   sourceRepo: 'default-npm-virtual'
   workingFolder: 'npm-example/'
   collectBuildInfo: true
   threads: '1'
   buildName: '$(Build.DefinitionName)'
   buildNumber: '$(Build.BuildNumber)'
```

And here is the package.json for this pipeline:
```
{
  "name": "npm-example",
  "version": "0.0.3",
  "scripts": {
    "start": "node helloworld"
  },
  "dependencies": {
    "send": "^0.16.2",
    "esbuild": "0.12.24"
  },
  "devDependencies": {
    "debug": "^4.1.1"
  }
}
```
