### ISSUE TITLE
Sign Docker image with Notation

### ISSUE THREAD

**Issue by Maetis** [jfrog/jfrog-cli#2077]
**Is your feature request related to a problem? Please describe.**
We want to use [Notation](https://notaryproject.dev/) during an CI/CD pipeline (Azure Pipelines) in order to sign Docker images.

Our problem turn around the credentials management. Our only option is to manage them "manually".

```yaml
- script: |
    notation login -u $REGISTRY_USER -p $REGISTRY_PASSWORD my.jfrog.io
    notation sign $IMAGE
  displayName: 'Sign Docker image'
```

**Describe the solution you'd like to see**
A new command for Notation in JFrog CLI.

```bash
$ jf rt notation
```
Credentials for Notation will be managed by JFrog CLI.

```yaml
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'my-connection'
    command: |
      jf rt notation sign $IMAGE
```
