### ISSUE TITLE
Hope the JFrog CLI support the third-party provider tokens for authentication

### ISSUE THREAD

**Issue by sjl0825** [jfrog/jfrog-cli#2576]
**Is your feature request related to a problem? Please describe.**
Currently, the JFrog CLI only supports Artifactory tokens for authentication, and does not support third-party provider tokens for authentication.  hope the JFrog CLI will support third-party provider tokens for authentication.
example: OIDC and other oauth 2.0 provider.

**Describe the solution you'd like to see**
It is expected that the JFrog CLI will be able to support authentication with tokens provided by third-party providers, such as: OIDC openid and other oauth 2.0 providers.

**Comment by yahavi** [comment]
@sjl0825
The JFrog CLI supports OIDC in the [Setup JFrog CLI](https://github.com/marketplace/actions/setup-jfrog-cli) GitHub Action. See also this [blog](https://jfrog.com/blog/secure-access-development-jfrog-github-oidc).

Each OIDC provider is unique and we plan to extend support to more CI servers.
Could you specify which third-party provider you are interested in for support?

**Comment by mgriffin13** [comment]
Not the OP, but it would be very helpful if the jfrog cli natively supported using Gitlab-CI's JWT.

**Comment by mgriffin13** [comment]
After I commented, I happened to notice that https://github.com/jfrog/jfrog-cli/pull/2938 was just merged and released this week, which solves my issue.

Here's an example using Gitlab-CI that I have working using jfrog cli version 2.75.0

```yaml
artifactory-job:
  id_tokens:
    JFROG_CLI_OIDC_EXCHANGE_TOKEN_ID:
      aud: https://artifactory.example.com
  script:
    - |
      jfrog c add \
        --url=https://artifactory.example.com \
        --oidc-audience=https://artifactory.example.com \
        --oidc-provider-name=gitlab \
        --oidc-provider-type=GenericOidc \
        --interactive=false
```
