### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by cschyma** [jfrog/jfrog-cli#347]
Currently there is no support for the dotnet CLI, e.g. restore of nuget dependencies via `jfrog rt nuget restore` does require the availability of nuget.

**Comment by cschyma** [comment]
Issue a JFrog's JIRA tracker: https://www.jfrog.com/jira/browse/RTFACT-18941

**Comment by jigar61** [comment]
We are having this issue as well since we are trying to report build information for a mix of projects that are .NET Framework and .NET Core. Has there been any progress on the above issue? I can't open the issue url above to see the status.

**Comment by eyalbe4** [comment]
@cschyma and @jigar61,
There's a pull request in progress for adding this functionality. See https://github.com/jfrog/jfrog-cli/pull/680.
We are planning to include this as part of the upcoming release.

**Comment by jigar61** [comment]
When is the release scheduled for? Is there a pre release version of the cli we can test on?

**Comment by eyalbe4** [comment]
@jigar61,
The release is planned for the end of this month. Getting feedback for this functionality is really important for us. We would really appreciate any feedback that you can provide. Would you like us to provide you with an unofficial pre release version with this functionality?

**Comment by jigar61** [comment]
Yes that will be great.

**Comment by jigar61** [comment]
Is this functionality still going to be a part of the end of the month release?

**Comment by eyalbe4** [comment]
@jigar61 - yes.
The above PR is in the final stages of code review. @liron-shalom did a great job developing this functionality.

**Comment by eyalbe4** [comment]
@@jigar61 and @cschyma,
Version 1.36.0 was released and includes the new **jfrog rt dotnet** command. You can read more about it [here](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildingNuGetPackages). We're really looking forward to your feedback for the new functionality. We'd like to make sure JFrog CLI's integration with the Dotnet Core CLI is flawless.

**Comment by jigar61** [comment]
Looks like this command only works for machines that have .NET Core 3.1.200 SDK and later versions. For the ones that have previous versions, I am seeing this error while running the command in debug mode.

error	29-May-2020 12:57:08	[Debug] Running command: Add sources. Output: Specify --help for a list of available options and commands.
error	29-May-2020 12:57:08	error: Unrecognized command or argument 'add'

Looking at the code, it looks like the cli internally depends on the "dotnet nuget add source" command that was added in .NET Core 3.1.200. Any way to get around that?

**Comment by liron-shalom** [comment]
@jigar61, thanks for your feedback!
We do use the `dotnet nuget add source` to dynamically write a valid NuGet configuration with the configured Artifactory's NuGet repository to use during the `dotnet restore` command.

Did you receive  the error message with the minimal version required?
We are are working on a way to create the NuGet configuration without the `source add` command, so we can support versions older to 3.0.0

**Comment by jigar61** [comment]
Yes I received this error when I ran the command on a machine that had .NET
core SDK 3.1.100. The error message itself did not say anything about a
minimum version.

**Comment by liron-shalom** [comment]
@jigar61 
A [pull request](https://github.com/jfrog/jfrog-cli/pull/720) with a fix is already in progress.
We're working to deliver this fast.

**Comment by jigar61** [comment]
I see that the pull request was merged. When can we expect the release?

**Comment by eyalbe4** [comment]
@jigar61,
We're planning to release this by the end of the week.

**Comment by jigar61** [comment]
I see the release notes for 1.37.0 but not the download itself. should I be looking somewhere else?

**Comment by eyalbe4** [comment]
@jigar61,
JFrog CLI 1.37.0 is now available. Looking forward to your feedback.

**Comment by cschyma** [comment]
> 
> 
> @@jigar61 and @cschyma,
> Version 1.36.0 was released and includes the new **jfrog rt dotnet** command. You can read more about it [here](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildingNuGetPackages). We're really looking forward to your feedback for the new functionality. We'd like to make sure JFrog CLI's integration with the Dotnet Core CLI is flawless.

Thank you very much! .NET Core support is working for us as expected! Finally we can use Xray in a much greater extent.

**Comment by eyalbe4** [comment]
Thank you for the feedback @cschyma! 
And thanks @liron-shalom for adding this functionality!

**Comment by dakimaz** [comment]
Can you include these changes into the Azure DevOps extension?

**Comment by dakimaz** [comment]
So I was super excited to see this released. But I'm having some issues with it. In the documentation it is stated that:

> Before using the nuget or dotnet commands, the nuget-config or dotnet-config commands should be used respectively.

However, in Azure DevOps returns an error with:
`##[error]Error: Command failed: /__t/jfrog/1.37.1/x64/jfrog rt dotnet-config --url="https://artifactory.server/" --user=*** --password=***`

`[Error] flag provided but not defined: -url
Incorrect Usage: flag provided but not defined: -url`

I'm not sure if this is an issue with the Azure DevOps extension of the jfrog CLI

**Comment by eyalbe4** [comment]
@dakimaz,

Thanks for reporting this issue!

Can you please try using the Artifactory Nuget or [Artifactory .NET Core tasks](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-TriggeringNugetand.NETCoreBuilds) added by the Artifactory Azure DevOps Extension, instead of the JFrog CLI task? These tasks do not require running the config commands (they run the config automatically behind the scenes, as you'll be able to see in the tasks logs).
We're looking forward to your feedback. 

We will look into the scenario of using the config commands from the JFrog CLI task itself. I'm not sure this is supposed currently, but we should at least consider adding some verification and better log messages in this scenario.

**Comment by dakimaz** [comment]
@eyalbe4 ,
Thanks for your quick reply! I just went on vacation but I will try when i get back.

We used to use the dotnet CLI tasks for azure, but have huge problems with getting credentials inside docker.
I will try the tasks you mentioned when i get back! Thanks a lot!

**Comment by dakimaz** [comment]
@eyalbe4 
As promised I have now tried it out. After some fiddling and changes to our setup I finally got it to work with:
```
    - task: ArtifactoryDotnetCore@1
      displayName: 'Restore Core Project'
      inputs:
        command: 'restore'
        arguments: '/P:Configuration=${{parameters.var_configuration}} /P:Framework=${{parameters.var_framework}}'
        artifactoryService: 'Artifactory Service'
        targetResolveRepo: 'nuget'
        rootPath: '${{parameters.var_core_proj}}'
        collectBuildInfo: true
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'
```
However we have to call this twice. Once for our core project and one for the test project.
Would it be possible to somehow specify more than one `rootPath` ?
Perhaps like so:
```
rootPath: >
${{parameters.var_core_proj}}
${{parameters.var_test_proj}}
```
In our case, using wildcards is not an option since we have even more project files.

**Comment by eyalbe4** [comment]
Thanks for feedback @dakimaz!
Specifying more than one root path is currently not supported. I guess you can duplicate this task and manage a task for each project you'd like to build. All projects can be merged into the same build-info, if you use the same build name and build number.
Let me know what you think.

**Comment by dakimaz** [comment]
Thanks again @eyalbe4 
Currently we _are_ duplicating the task. On our end we might come to a solution which enables us to use the wild card. But I think supporting multiple project files should be supported. It would be a very nice feature!

But thanks a lot for all your help! (yay for no API keys in .yml/clear text.)

**Comment by dakimaz** [comment]
Hello @eyalbe4  sorry for hijacking you again.
But i just wanted to let you know, that it is possible to specify more than one root path and I wanted to share it with you
```
    - task: ArtifactoryDotnetCore@1
      displayName: 'Restore Core Project'
      inputs:
        command: 'restore'
        arguments: '/P:Configuration=${{parameters.var_configuration}} /P:Framework=${{parameters.var_framework}}'
        artifactoryService: 'Artifactory Service'
        targetResolveRepo: 'nuget'
        rootPath: |
           **/first.csproj;
           **/second.csproj
        collectBuildInfo: true
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'
```
It adheres to the [file matching patterns](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops). I think it would be very user friendly if you mentioned this in the documentation for your task as it is not super intuitive what the syntax is. 😊
