### ISSUE TITLE
jfrog rt helm chart upload leads to invalid index in artifactory

### ISSUE THREAD

**Issue by milosgajdos** [jfrog/jfrog-cli#686]
We would love to use this handy cli tool for uploading our helm charts to artifactory, however during testing we noticed a strange thing. Once the chart is successfully uploaded and the new helm repo index is generated we can see the chart `urls` field in the index to be set to **local** URL as opposed to the artifactory URL. Let me give you an example.

This is the command we use to upload a chart:
```
jfrog rt upload --url=https://artifactory-domain-name/ --apikey="XXXX" chartXYZ-0.0.1.tgz helm-apps
```

Now this upload succeeds just fine, but once artifactory regenerates the helm repo index the just uploaded chart has the following entry in it:
```yaml
...
chartXYZ:
  - apiVersion: v2
    created: 2020-05-05T15:35:35.572Z
    description: A Helm chart for XYZ
    digest: 650a6a262af9e4f97ab485b5a6f106c3f38f6d41e9587c2de7d8d1ff0dcd23d8
    name: chartXYZ
    urls:
    - local://chartXYZ-0.0.1.tgz
    version: 0.0.1
generated: 2020-05-05T15:35:35.572Z
...
```

Note the `urls` key: it's set to **local** file as opposed to what we would expect:
```
https://artifactory-domain-name/helm-apps/chartXYZ-0.0.1.tgz
```

Are we missing anything or is this is a bug?

**Comment by eyalbe4** [comment]
@milosgajdos,
If I understand correct, the issue you're describing does not occur when you're using the helm client to upload your helm charts to Artiofactory.
If this is the case, let's check what are the differences between the requests sent to Artifactory by helm and the above upload command of JFrog CLI.
To help you see all incoming requests, you can look at Artifactory's requests.log (also available from the UI).

**Comment by milosgajdos** [comment]
@eyalbe4 I'm not sure you can upload your helm charts to artifactory using helm client. If yes, please do let me know how. We do the following:
1 `helm package` + `helm merge` artifactory index with the locally generated file
2. run our own shell script which wraps `curl` commands which are POST-ing both the newly generated index and the packaged helm chart into artifactory

As I said, the issue is not that the chart is not getting uploaded. It does get uploaded as I said in the original issue, the problem is THE ARTIFACTORY INDEX indexes the newly uploaded chart as **local file** as opposed to the full artifactory URL. This only happens when using the jfrog cli.

**Comment by milosgajdos** [comment]
This has got nowhere in 2 months. Closing it as it clearly doesn’t seem to matter to jfrog.

**Comment by eyalbe4** [comment]
@milosgajdos,

Apologies for not being able to reply to you earlier.

We weren't able to reproduce the issue as you described it. Could it be that you downloaded the file from the local repository and not through the virtual one?
Have a look at the following index file. In both cases, I'm looking at the exact same chart index, but the first file was downloaded directly from the local repo, and the second one was downloaded from a virtual repo (which includes the local).

**Local:**
```
apiVersion: v1
entries:
  acs-engine-autoscaler:
  - apiVersion: v1
    appVersion: 2.1.1
    created: 2019-08-07T13:44:31.486Z
    deprecated: true
    description: DEPRECATED Scales worker nodes within agent pools
    home: https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    name: acs-engine-autoscaler
    sources:
    - https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler
    urls:
    - local://acs-engine-autoscaler-2.2.2.tgz
    version: 2.2.2
  aerospike:
  - appVersion: v3.14.1.2
    created: 2019-08-07T13:44:31.519Z
    description: A Helm chart for Aerospike in Kubernetes
    home: http://aerospike.com
    icon: https://s3-us-west-1.amazonaws.com/aerospike-fd/wp-content/uploads/2016/06/Aerospike_square_logo.png
    keywords:
    - aerospike
    - big-data
    maintainers:
    - email: k.mousavizamani@travelaudience.com
      name: kavehmzta
    name: aerospike
    sources:
    - https://github.com/aerospike/aerospike-server
    urls:
    - local://aerospike-0.1.5.tgz
    version: 0.1.5
generated: 2019-08-07T13:45:04.437Z
```

**Virtual:**
```
apiVersion: v1
entries:
  acs-engine-autoscaler:
  - apiVersion: v1
    appVersion: 2.1.1
    created: 2019-08-07T13:44:31.486Z
    deprecated: true
    description: DEPRECATED Scales worker nodes within agent pools
    home: https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    name: acs-engine-autoscaler
    sources:
    - https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler
    urls:
    - https://yehudah.jfrog.io/artifactory/helm-virtual/acs-engine-autoscaler-2.2.2.tgz
    version: 2.2.2
  aerospike:
  - appVersion: v3.14.1.2
    created: 2019-08-07T13:44:31.519Z
    description: A Helm chart for Aerospike in Kubernetes
    home: http://aerospike.com
    icon: https://s3-us-west-1.amazonaws.com/aerospike-fd/wp-content/uploads/2016/06/Aerospike_square_logo.png
    keywords:
    - aerospike
    - big-data
    maintainers:
    - email: k.mousavizamani@travelaudience.com
      name: kavehmzta
    name: aerospike
    sources:
    - https://github.com/aerospike/aerospike-server
    urls:
    - https://yehudah.jfrog.io/artifactory/helm-virtual/aerospike-0.1.5.tgz
    version: 0.1.5
generated: 2019-08-07T13:45:04.437Z
```

In addition, please notice the **Virtual Repositories Only** warning on the [documentation](https://www.jfrog.com/confluence/display/JFROG/Helm+Chart+Repositories#HelmChartRepositories-ResolvingHelmCharts).

Please let me know if this si indeed the root cause of your issue, and if I can be of further help.
