### ISSUE TITLE
Jfrog rt dpl 400 Bad Request Error

### ISSUE THREAD

**Issue by supratim-persistent** [jfrog/jfrog-cli#934]
**Description**
`Using JFrog CLI version 1.40.0 to pull an image from the Artifactory private registry and using Github actions to run the cli, while the cli set up and login is successful and even the image gets pulled and is available locally, there is error below that keeps coming and the CICD step fails.
400 Bad Request Error`

**Steps to reproduce**
Run the below steps in a Gihub actions pipeline
```
- name: SETUP JFROG
   uses: jfrog/setup-jfrog-cli@v1
   with:
     version: 1.39.4
   env:
    JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_DEPLOYER }}

- name: Docker Pull
    run: |
      jfrog rt dpl --server-id xyz <repo_name>.jfrog.io/ecs-runner-helpers:v5 https://<source_repository>
```

**No 400 Bad Request Error**
Ideally after the image gets pulled through jfrog rt dpl, no 400 bad request error should come.

**Versions**
- JFrog CLI version: 1.40.0
- JFrog CLI operating system: ubuntu:latest
- Artifactory Version:

**Additional Error Details from pipeline**
```
[Info] Getting repository 'https://<repo_name>/artifactory/abc-local' details ...
Error:  Artifactory response: 400 Bad Request
{
  "errors": [
    {
      "status": 400,
      "message": "Bad Request"
    }
  ]
}
Error: Process completed with exit code 1.
```
